### ISSUE TITLE
Add codecov file

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#337]
Add codecov file in project root:

```
comment: no # do not comment PR with the result

coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    project: # settings affecting project coverage
      default:
        target: auto # auto % coverage target
        threshold: 5%  # allow for 5% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: false
```
